name: Deploy Documentation to Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20.18.2
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Generate documentation
        run: npm run generate

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation-build-staging
          path: |
            .output/public
            firebase.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20.18.2
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_STAGING }}
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: documentation-build-staging
          path: .

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.FIREBASE_DEPLOY_STAGING }}" > firebaselogin.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebaselogin.json

      - name: Deploy to Firebase (Staging)
        run: firebase deploy --project ${{ secrets.FIREBASE_PROJECT_ID_STAGING }}
